import{S as L,i as p,a as S}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function y({hits:t}){const o=document.querySelector(".gallery-container"),s=t.map(({webformatURL:i,largeImageURL:e,tags:r,likes:a,views:h,comments:b,downloads:w})=>`<ul class="gallery-card">
      <li class="gallery">
      <a class="gallery-link" href="${e}"> 
   <img src="${i}" alt="${r}" width="270" height="160"/>
   </a>
    <div class="discrabe">
  <ul class="discrabe-list">
  <li class="discrabe-item"><b>Likes</b> ${a}</li>
  <li class="discrabe-item"><b>Views</b> ${h}</li>
  <li class="discrabe-item"><b>Comments</b> ${b}</li>
  <li class="discrabe-item"><b>Downloads</b> ${w}</li>
  </ul>
</div>
</li>
    </ul>`).join("");if(o.insertAdjacentHTML("beforeend",s),t.length===0)return n(),l();new L(".gallery a",{captionDelay:250,captionData:"alt",captionPosting:"bottom"}).refresh(),n()}function g(){const t=document.querySelector(".loading");t.style.display="flex"}function n(){const t=document.querySelector(".loading");t.style.display="none"}function l(){p.error({title:"Error",position:"topRight",title:"",message:"Sorry, there are no images matching your search query. Please try again!"})}function P(){p.warning({title:"warning",position:"topRight",title:"",message:"We are sorry, but you`ve reached the end of search results!",backgroundColor:"blue",titleColor:"white",messageColor:"white"})}async function f(t,o){const i={key:"44790874-b72b714502b79af1442269c5d",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};try{return(await S.get("https://pixabay.com/api/",{params:i})).data}catch(e){throw new Error(e.response.status)}}const q=document.querySelector(".search-form"),m=document.querySelector(".gallery-container"),u=document.querySelector(".btn-load");let d="",c=1;q.addEventListener("submit",v);u.addEventListener("click",$);async function v(t){t.preventDefault();const o=t.currentTarget,s=o.elements.inputtext.value.toLowerCase().trim();if(s==="")return n(),l();g(),m.innerHTML="",d=s,c=1;try{const i=await f(d,c);if(i.hits.length===0)return u.style.display="none",n(),l();y(i),u.style.display="flex"}catch{l()}finally{o.reset(),n()}}async function $(){g(),c+=1;const t=60/15;try{c===t&&(u.style.display="none",P());const o=await f(d,c);y(o),m.scrollIntoView({behavior:"smooth",block:"start"});let i=document.querySelector(".gallery").getBoundingClientRect();window.scrollBy({top:i.height*2,left:0,behavior:"smooth"})}catch{l()}finally{n()}}
//# sourceMappingURL=commonHelpers.js.map
